name: e3doubt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pytest
  - fortran-compiler
  - matplotlib=3.10.9
  - numpy=2.4.6
  - pandas=3.0.3
  - rpy2=3.6.7
  - r-ggplot2
  - setuptools
  - xarray=2026.4.0
  - pip:
    - apexpy==2.1.0
    - iri2016==1.11.1
    - pymsis==0.12.0
    - ppigrf==2.1.0


