name: e3doubt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - pytest
  - fortran-compiler
  - matplotlib=3.6
  - setuptools
  - numpy=1.23
  - pandas=1.5
  - rpy2=3.5.11
  - r-ggplot2
  - xarray=2022.10
  - pip:
    - apexpy==1.1.0
    - iri2016==1.11.1
    - pymsis==0.8.0
    - ppigrf==1.0.0


